issues:
  exclude-files:
    - main.go
run:
  build-tags:
    - codeanalysis
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupword
    - misspell
    - musttag
    - nolintlint
    - perfsprint
    - prealloc
    - tenv
    - unparam
    - unconvert
    - wastedassign
