issues:
  exclude-files:
    - main.go
  max-same-issues: 50
run:
  build-tags:
    - codeanalysis
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - goconst
    - gocritic
    - gofumpt
    - misspell
    - musttag
    - nolintlint
    - perfsprint
    - prealloc
    - tenv
    - unparam
    - unconvert
    - wastedassign
