// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {artifact} from '../models';
import {collection} from '../models';
import {secret} from '../models';
import {auth} from '../models';
import {aggregate} from '../models';
import {consumerapi} from '../models';

export function ArtifactRefForRuntimeServerID(arg1:server.ServerID):Promise<artifact.ArtifactRef>;

export function CollectionRefForRuntimeCatalogID(arg1:server.CatalogID):Promise<collection.CollectionRef>;

export function DeleteMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string):Promise<void>;

export function GetMCPServerAuthHealth(arg1:artifact.ArtifactRef):Promise<auth.MCPAuthHealth>;

export function PurgeMCPBundle(arg1:collection.CollectionRef,arg2:number):Promise<void>;

export function PutMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string,arg4:string):Promise<aggregate.SecretWriteResult>;

export function RefreshMCPBundle(arg1:collection.CollectionRef):Promise<consumerapi.Bundle>;

export function ReplaceMCPBundleDocument(arg1:consumerapi.ReplaceDocumentRequest):Promise<consumerapi.Bundle>;

export function RetireMCPBundle(arg1:collection.CollectionRef,arg2:number):Promise<collection.Collection>;

export function RuntimeCatalogIDForCollection(arg1:collection.CollectionRef):Promise<server.CatalogID>;

export function RuntimeServerIDForArtifact(arg1:artifact.ArtifactRef):Promise<server.ServerID>;

export function UpdateMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:server.ServerData):Promise<artifact.Artifact>;

export function UpdateProtectedMCPBundleInstallation(arg1:collection.CollectionRef,arg2:number,arg3:boolean):Promise<void>;

export function UpdateProtectedMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean,arg4:server.ServerData):Promise<void>;
