// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {collection} from '../models';
import {artifact} from '../models';
import {server} from '../models';
import {root} from '../models';

export function CreateMCPBundle(arg1:store.CreateRequest):Promise<store.Bundle>;

export function GetMCPBundle(arg1:collection.CollectionRef):Promise<store.Bundle>;

export function GetMCPBundleDocument(arg1:collection.CollectionRef):Promise<store.BundleDocument>;

export function GetMCPBundleInstallation(arg1:collection.CollectionRef):Promise<store.BundleInstallationView>;

export function GetMCPServerInstallation(arg1:artifact.ArtifactRef):Promise<store.ServerInstallationView>;

export function InspectMCPPolicy(arg1:artifact.ArtifactRef):Promise<store.PolicyView>;

export function InspectMCPServer(arg1:artifact.ArtifactRef):Promise<server.Resolved>;

export function ListMCPBundlePolicies(arg1:collection.CollectionRef):Promise<Array<artifact.Artifact>>;

export function ListMCPBundleServers(arg1:collection.CollectionRef):Promise<Array<artifact.Artifact>>;

export function ListMCPBundles(arg1:root.RootID):Promise<Array<store.Bundle>>;
