// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMCPBundle(arg1) {
  return window['go']['main']['MCPStoreWrapper']['CreateMCPBundle'](arg1);
}

export function GetMCPBundle(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPBundle'](arg1);
}

export function GetMCPBundleDocument(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPBundleDocument'](arg1);
}

export function GetMCPBundleInstallation(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPBundleInstallation'](arg1);
}

export function GetMCPServerInstallation(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPServerInstallation'](arg1);
}

export function GetMCPServerSchemaIdentity() {
  return window['go']['main']['MCPStoreWrapper']['GetMCPServerSchemaIdentity']();
}

export function InspectMCPPolicy(arg1) {
  return window['go']['main']['MCPStoreWrapper']['InspectMCPPolicy'](arg1);
}

export function InspectMCPServer(arg1) {
  return window['go']['main']['MCPStoreWrapper']['InspectMCPServer'](arg1);
}

export function ListMCPBundlePolicies(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPBundlePolicies'](arg1);
}

export function ListMCPBundleServers(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPBundleServers'](arg1);
}

export function ListMCPBundles(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPBundles'](arg1);
}

export function ListMCPBundlesForManagement() {
  return window['go']['main']['MCPStoreWrapper']['ListMCPBundlesForManagement']();
}

export function UpdateBundleEnabled(arg1, arg2, arg3) {
  return window['go']['main']['MCPStoreWrapper']['UpdateBundleEnabled'](arg1, arg2, arg3);
}
