// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';
import {collection} from '../models';

export function CreateMCPBundle(arg1:consumerapi.CreateMCPBundleRequest):Promise<consumerapi.CreateMCPBundleResponse>;

export function GetMCPBundle(arg1:consumerapi.GetMCPBundleRequest):Promise<consumerapi.GetMCPBundleResponse>;

export function GetMCPBundleDocument(arg1:consumerapi.GetMCPBundleDocumentRequest):Promise<consumerapi.GetMCPBundleDocumentResponse>;

export function GetMCPBundleInstallation(arg1:consumerapi.GetMCPBundleInstallationRequest):Promise<consumerapi.GetMCPBundleInstallationResponse>;

export function GetMCPServerInstallation(arg1:consumerapi.GetMCPServerInstallationRequest):Promise<consumerapi.GetMCPServerInstallationResponse>;

export function GetMCPServerSchemaIdentity():Promise<consumerapi.MCPServerSchemaIdentity>;

export function InspectMCPPolicy(arg1:consumerapi.InspectMCPPolicyRequest):Promise<consumerapi.InspectMCPPolicyResponse>;

export function InspectMCPServer(arg1:consumerapi.InspectMCPServerRequest):Promise<consumerapi.InspectMCPServerResponse>;

export function ListMCPBundlePolicies(arg1:consumerapi.ListMCPBundlePoliciesRequest):Promise<consumerapi.ListMCPBundlePoliciesResponse>;

export function ListMCPBundleServers(arg1:consumerapi.ListMCPBundleServersRequest):Promise<consumerapi.ListMCPBundleServersResponse>;

export function ListMCPBundles(arg1:consumerapi.ListMCPBundlesRequest):Promise<consumerapi.ListMCPBundlesResponse>;

export function ListMCPBundlesForManagement():Promise<Array<consumerapi.Bundle>>;

export function UpdateBundleEnabled(arg1:collection.CollectionRef,arg2:number,arg3:boolean):Promise<consumerapi.Bundle>;
