// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';
import {aggregate} from '../models';
import {collection} from '../models';
import {runtime} from '../models';

export function ResolveArtifactSkill(arg1:artifact.ArtifactRef):Promise<aggregate.ResolvedArtifactSkill>;

export function RuntimeCatalogIDForCollection(arg1:collection.CollectionRef):Promise<runtime.CatalogID>;
