// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AdoptSkill'](arg1);
}

export function AttachSkillBundleSource(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AttachSkillBundleSource'](arg1);
}

export function CreateManagedSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateManagedSkill'](arg1);
}

export function CreateSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateSkillBundle'](arg1);
}

export function GetManagedSkillDocument(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetManagedSkillDocument'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkill'](arg1);
}

export function GetSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkillBundle'](arg1);
}

export function ListBundleSkills(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListBundleSkills'](arg1);
}

export function ListSkillBundles(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillBundles'](arg1);
}

export function ListSkillBundlesForManagement() {
  return window['go']['main']['SkillStoreWrapper']['ListSkillBundlesForManagement']();
}

export function PinSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PinSkill'](arg1);
}

export function PurgeSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PurgeSkill'](arg1);
}

export function PurgeSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PurgeSkillBundle'](arg1);
}

export function RefreshSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RefreshSkillBundle'](arg1);
}

export function RegisterSkillBundleDirectory(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RegisterSkillBundleDirectory'](arg1);
}

export function RetireSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RetireSkillBundle'](arg1);
}

export function SetSkillEnabled(arg1) {
  return window['go']['main']['SkillStoreWrapper']['SetSkillEnabled'](arg1);
}

export function UnadoptSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['UnadoptSkill'](arg1);
}

export function UpdateSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['UpdateSkillBundle'](arg1);
}
