// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';
import {domain} from '../models';

export function AdoptSkill(arg1:consumerapi.AdoptSkillRequest):Promise<consumerapi.AdoptSkillResponse>;

export function AttachSkillBundleSource(arg1:consumerapi.AttachSkillBundleSourceRequest):Promise<consumerapi.AttachSkillBundleSourceResponse>;

export function CreateManagedSkill(arg1:consumerapi.CreateManagedSkillRequest):Promise<consumerapi.CreateManagedSkillStoreResponse>;

export function CreateSkillBundle(arg1:consumerapi.CreateSkillBundleRequest):Promise<consumerapi.CreateSkillBundleResponse>;

export function GetManagedSkillDocument(arg1:consumerapi.GetManagedSkillDocumentRequest):Promise<consumerapi.GetManagedSkillDocumentResponse>;

export function GetSkill(arg1:consumerapi.GetSkillRequest):Promise<consumerapi.GetSkillResponse>;

export function GetSkillBundle(arg1:consumerapi.GetSkillBundleRequest):Promise<consumerapi.GetSkillBundleResponse>;

export function ListBundleSkills(arg1:consumerapi.ListBundleSkillsRequest):Promise<consumerapi.ListBundleSkillsResponse>;

export function ListSkillBundles(arg1:consumerapi.ListSkillBundlesRequest):Promise<consumerapi.ListSkillBundlesResponse>;

export function ListSkillBundlesForManagement():Promise<Array<domain.SkillBundle>>;

export function PinSkill(arg1:consumerapi.PinSkillRequest):Promise<consumerapi.PinSkillResponse>;

export function PurgeSkill(arg1:consumerapi.PurgeSkillRequest):Promise<consumerapi.PurgeSkillResponse>;

export function PurgeSkillBundle(arg1:consumerapi.PurgeSkillBundleRequest):Promise<consumerapi.PurgeSkillBundleResponse>;

export function RefreshSkillBundle(arg1:consumerapi.RefreshSkillBundleRequest):Promise<consumerapi.RefreshSkillBundleResponse>;

export function RegisterSkillBundleDirectory(arg1:consumerapi.RegisterSkillBundleDirectoryRequest):Promise<consumerapi.RegisterSkillBundleDirectoryResponse>;

export function RetireSkillBundle(arg1:consumerapi.RetireSkillBundleRequest):Promise<consumerapi.RetireSkillBundleResponse>;

export function SetSkillEnabled(arg1:consumerapi.SetSkillEnabledRequest):Promise<consumerapi.SetSkillEnabledResponse>;

export function UnadoptSkill(arg1:consumerapi.UnadoptSkillRequest):Promise<consumerapi.UnadoptSkillResponse>;

export function UpdateSkillBundle(arg1:consumerapi.UpdateSkillBundleRequest):Promise<consumerapi.UpdateSkillBundleResponse>;
