// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bundle} from '../models';
import {artifact} from '../models';
import {collection} from '../models';
import {root} from '../models';
import {store} from '../models';

export function AdoptSkill(arg1:bundle.AdoptSkillRequest):Promise<artifact.Artifact>;

export function AttachSkillSource(arg1:collection.CollectionRef,arg2:number,arg3:bundle.AttachmentDraft):Promise<bundle.Bundle>;

export function CreateManagedSkill(arg1:bundle.CreateManagedSkillRequest):Promise<bundle.CreateManagedSkillResponse>;

export function CreateSkillBundle(arg1:bundle.CreateBundleRequest):Promise<bundle.Bundle>;

export function GetManagedSkillDocument(arg1:artifact.ArtifactRef):Promise<bundle.ManagedSkillDocument>;

export function GetSkillBundle(arg1:collection.CollectionRef):Promise<bundle.Bundle>;

export function ListBundleSkills(arg1:collection.CollectionRef):Promise<Array<artifact.Artifact>>;

export function ListSkillBundles(arg1:root.RootID):Promise<Array<bundle.Bundle>>;

export function PinSkill(arg1:bundle.PinSkillRequest):Promise<artifact.Artifact>;

export function PurgeSkill(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function PurgeSkillBundle(arg1:collection.CollectionRef,arg2:number):Promise<void>;

export function RefreshSkillBundle(arg1:collection.CollectionRef):Promise<void>;

export function ResolveArtifactSkill(arg1:artifact.ArtifactRef):Promise<store.ResolvedArtifactSkill>;

export function RetireSkillBundle(arg1:collection.CollectionRef,arg2:number):Promise<collection.Collection>;

export function SetSkillEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<artifact.Artifact>;

export function UnadoptSkill(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<void>;

export function UpdateSkillBundle(arg1:bundle.UpdateBundleRequest):Promise<bundle.Bundle>;
