// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResolveArtifactSkill(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['ResolveArtifactSkill'](arg1);
}

export function RuntimeCatalogIDForCollection(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['RuntimeCatalogIDForCollection'](arg1);
}
