// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';

export function ComposeWorkspaceContext(arg1:consumerapi.ComposeWorkspaceContextRequest):Promise<consumerapi.ComposeWorkspaceContextResponse>;

export function ListWorkspaceContexts(arg1:consumerapi.ListWorkspaceContextsRequest):Promise<consumerapi.ListWorkspaceContextsResponse>;

export function ListWorkspaceSkills(arg1:consumerapi.ListWorkspaceSkillsRequest):Promise<consumerapi.ListWorkspaceSkillsResponse>;

export function LoadWorkspaceContexts(arg1:consumerapi.LoadWorkspaceContextsRequest):Promise<consumerapi.LoadWorkspaceContextsResponse>;

export function LoadWorkspaceSkills(arg1:consumerapi.LoadWorkspaceSkillsRequest):Promise<consumerapi.LoadWorkspaceSkillsResponse>;
