// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {consumerapi} from '../models';
import {source} from '../models';
import {artifact} from '../models';

export function AdoptWorkspaceOccurrence(arg1:collection.CollectionRef,arg2:consumerapi.AdoptWorkspaceOccurrenceInput):Promise<consumerapi.WorkspaceArtifactView>;

export function AttachWorkspaceSource(arg1:collection.CollectionRef,arg2:consumerapi.AttachWorkspaceSourceInput):Promise<consumerapi.WorkspaceView>;

export function CreateEmptyWorkspace(arg1:consumerapi.CreateEmptyWorkspaceInput):Promise<consumerapi.WorkspaceView>;

export function CreateFilesystemWorkspace(arg1:consumerapi.CreateFilesystemWorkspaceInput):Promise<consumerapi.WorkspaceView>;

export function DetachWorkspaceSource(arg1:collection.CollectionRef,arg2:consumerapi.DetachWorkspaceSourceInput):Promise<consumerapi.WorkspaceView>;

export function GetWorkspace(arg1:consumerapi.GetWorkspaceRequest):Promise<consumerapi.GetWorkspaceResponse>;

export function GetWorkspaceArtifact(arg1:consumerapi.GetWorkspaceArtifactRequest):Promise<consumerapi.GetWorkspaceArtifactResponse>;

export function GetWorkspaceCatalog(arg1:consumerapi.GetWorkspaceCatalogRequest):Promise<consumerapi.GetWorkspaceCatalogResponse>;

export function ListWorkspaceArtifacts(arg1:consumerapi.ListWorkspaceArtifactsRequest):Promise<consumerapi.ListWorkspaceArtifactsResponse>;

export function ListWorkspaceSourcesForManagement():Promise<Array<source.Summary>>;

export function ListWorkspaceSuppressions(arg1:collection.CollectionRef):Promise<Array<consumerapi.WorkspaceSuppressionView>>;

export function ListWorkspaces(arg1:consumerapi.ListWorkspacesRequest):Promise<consumerapi.ListWorkspacesResponse>;

export function PinWorkspaceArtifact(arg1:collection.CollectionRef,arg2:consumerapi.PinWorkspaceArtifactInput):Promise<consumerapi.WorkspaceArtifactView>;

export function PurgeWorkspace(arg1:collection.CollectionRef,arg2:number):Promise<collection.CollectionRef>;

export function PurgeWorkspaceArtifact(arg1:collection.CollectionRef,arg2:artifact.ArtifactRef,arg3:number):Promise<artifact.ArtifactRef>;

export function RefreshWorkspace(arg1:collection.CollectionRef):Promise<consumerapi.WorkspaceRefreshResult>;

export function RegisterWorkspaceDirectory(arg1:collection.CollectionRef,arg2:consumerapi.RegisterWorkspaceDirectoryInput):Promise<consumerapi.WorkspaceDirectoryRegistrationResult>;

export function RetireWorkspace(arg1:collection.CollectionRef,arg2:number):Promise<consumerapi.RetireWorkspaceResult>;

export function SetWorkspaceArtifactEnabled(arg1:collection.CollectionRef,arg2:artifact.ArtifactRef,arg3:number,arg4:boolean):Promise<consumerapi.WorkspaceArtifactView>;

export function SetWorkspacePrimarySource(arg1:collection.CollectionRef,arg2:consumerapi.SetWorkspacePrimarySourceInput):Promise<consumerapi.WorkspaceView>;

export function SetWorkspaceSourceEnabled(arg1:string,arg2:number,arg3:boolean):Promise<source.Summary>;

export function SuppressWorkspaceBinding(arg1:collection.CollectionRef,arg2:consumerapi.SuppressWorkspaceBindingInput):Promise<consumerapi.WorkspaceSuppressionView>;

export function UnadoptWorkspaceArtifact(arg1:collection.CollectionRef,arg2:artifact.ArtifactRef,arg3:consumerapi.UnadoptWorkspaceArtifactInput):Promise<consumerapi.UnadoptWorkspaceArtifactResult>;

export function UnsuppressWorkspaceBinding(arg1:collection.CollectionRef,arg2:artifact.SourceBinding,arg3:number):Promise<consumerapi.UnsuppressWorkspaceBindingResult>;

export function UpdateWorkspace(arg1:collection.CollectionRef,arg2:consumerapi.UpdateWorkspaceInput):Promise<consumerapi.WorkspaceView>;

export function UpdateWorkspaceAttachment(arg1:collection.CollectionRef,arg2:consumerapi.UpdateWorkspaceAttachmentInput):Promise<consumerapi.WorkspaceView>;
