// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';

export function SetWorkspaceArtifactRuntimeDisabled(arg1:consumerapi.SetWorkspaceArtifactRuntimeDisabledRequest):Promise<consumerapi.SetWorkspaceArtifactRuntimeDisabledResponse>;
