// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComposeWorkspaceContext(arg1) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['ComposeWorkspaceContext'](arg1);
}

export function ListWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['ListWorkspaceContexts'](arg1);
}

export function ListWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['ListWorkspaceSkills'](arg1);
}

export function LoadWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['LoadWorkspaceContexts'](arg1);
}

export function LoadWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['LoadWorkspaceSkills'](arg1);
}
