// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptWorkspaceOccurrence(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['AdoptWorkspaceOccurrence'](arg1, arg2);
}

export function AttachWorkspaceSource(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['AttachWorkspaceSource'](arg1, arg2);
}

export function CreateEmptyWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['CreateEmptyWorkspace'](arg1);
}

export function CreateFilesystemWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['CreateFilesystemWorkspace'](arg1);
}

export function DetachWorkspaceSource(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['DetachWorkspaceSource'](arg1, arg2);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspace'](arg1);
}

export function GetWorkspaceArtifact(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspaceArtifact'](arg1);
}

export function GetWorkspaceCatalog(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspaceCatalog'](arg1);
}

export function ListWorkspaceArtifacts(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceArtifacts'](arg1);
}

export function ListWorkspaceSourcesForManagement() {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceSourcesForManagement']();
}

export function ListWorkspaceSuppressions(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceSuppressions'](arg1);
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaces'](arg1);
}

export function PinWorkspaceArtifact(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['PinWorkspaceArtifact'](arg1, arg2);
}

export function PurgeWorkspace(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['PurgeWorkspace'](arg1, arg2);
}

export function PurgeWorkspaceArtifact(arg1, arg2, arg3) {
  return window['go']['main']['WorkspaceStoreWrapper']['PurgeWorkspaceArtifact'](arg1, arg2, arg3);
}

export function RefreshWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['RefreshWorkspace'](arg1);
}

export function RegisterWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['RegisterWorkspaceDirectory'](arg1, arg2);
}

export function RetireWorkspace(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['RetireWorkspace'](arg1, arg2);
}

export function SetWorkspaceArtifactEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspaceArtifactEnabled'](arg1, arg2, arg3, arg4);
}

export function SetWorkspacePrimarySource(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspacePrimarySource'](arg1, arg2);
}

export function SetWorkspaceSourceEnabled(arg1, arg2, arg3) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspaceSourceEnabled'](arg1, arg2, arg3);
}

export function SuppressWorkspaceBinding(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['SuppressWorkspaceBinding'](arg1, arg2);
}

export function UnadoptWorkspaceArtifact(arg1, arg2, arg3) {
  return window['go']['main']['WorkspaceStoreWrapper']['UnadoptWorkspaceArtifact'](arg1, arg2, arg3);
}

export function UnsuppressWorkspaceBinding(arg1, arg2, arg3) {
  return window['go']['main']['WorkspaceStoreWrapper']['UnsuppressWorkspaceBinding'](arg1, arg2, arg3);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['UpdateWorkspace'](arg1, arg2);
}

export function UpdateWorkspaceAttachment(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['UpdateWorkspaceAttachment'](arg1, arg2);
}
