name: Flatpak
run-name: ${{ github.ref_name }} - Building Flatpak
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '0.0.1'
jobs:
  build-flatpak:
    name: 'Flatpak'
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: 'FlexiGPT'
      NODE_VERSION: '20.18.0'
      FLATPAK_ID: 'io.github.flexigpt.Client'
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: 'Determine prerequisites'
        id: prereq
        run: |
          echo "need_node=$(command -v node >/dev/null 2>&1 && echo 0 || echo 1)" >> $GITHUB_OUTPUT

      # Consider switching to https://github.com/actions/setup-node when it works
      # https://github.com/nektos/act/issues/973
      - name: Install node
        if: ${{ steps.prereq.outputs.need_node == '1' }}
        run: |
          if [ "${RUNNER_OS,,}" = "windows" ]
          then
            choco install nodejs -y --version=${{ env.NODE_VERSION }}
            echo "C:\Program Files\nodejs" >> $GITHUB_PATH
          else
            curl -sS https://webi.sh/node@${{ env.NODE_VERSION }} | sh
            echo ~/.local/opt/node/bin >> $GITHUB_PATH
          fi

      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: packaging/flatpak/${{env.FLATPAK_ID}}.yml
          cache-key: flatpak-builder-${{ github.sha }}
          bundle: ${{ env.BUILD_NAME }}.flatpak

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}-linux-amd64
          path: |
            ${{ env.BUILD_NAME }}.flatpak

      - name: 'Add to release'
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.BUILD_NAME }}.flatpak
